<a href="https://colab.research.google.com/github/Darshan0805/AML-Project/blob/main/2348548_Lab10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
import random

# Define the rooms and doors
rooms = [0, 1, 2, 3, 4, 5]
doors = [(0,1), (0,4), (1,2), (2,3), (3,4), (4,5), (1,5)]

# Define Q-value matrix
Q = np.zeros((len(rooms), len(rooms)))

# Define parameters
alpha = 0.8
gamma = 0.9
epsilon = 0.1

# Initialize Q-values arbitrarily
print("Initial Q-values:")
print(Q)

# Train over 10000 iterations
for i in range(10000):
  # Get current room
  current_room = random.randint(0,len(rooms)-1)

  # Get next room using epsilon-greedy strategy
  if random.random() < epsilon:
    next_room = random.randint(0,len(rooms)-1)
  else:
    next_room = np.argmax(Q[current_room])

  # Get reward
  reward = -1
  if current_room == next_room:
    reward = 0
  elif (current_room, next_room) in doors:
    reward = -1
  else:
    reward = -10

  # Update Q-value
  Q[current_room, next_room] = Q[current_room, next_room] + alpha*(reward + gamma*np.max(Q[next_room]) - Q[current_room, next_room])

# Print final Q-values
print("\nFinal Q-values:")
print(Q)

Initial Q-values:
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

Final Q-values:
[[  0.  -1. -10. -10.  -1. -10.]
 [-10.   0.  -1. -10. -10.  -1.]
 [-10. -10.   0.  -1. -10. -10.]
 [-10. -10. -10.   0.  -1. -10.]
 [-10. -10. -10. -10.   0.  -1.]
 [-10. -10. -10. -10. -10.   0.]]
